version: "3.9"

x-default_service: &default_service
  build:
    context: .
  volumes:
    - .:/usr/src/app
  env_file:
    - .env
  tty: true
  stdin_open: true

services:
  orchestrator:
    <<: *default_service
    container_name: shop-http-orch
    command: bundle exec rackup --host=0.0.0.0
    # depends_on:
      # message_broker:
      #   condition: service_healthy
      # postgres:
      #   condition: service_started

networks:
  default:
      name: shop-local-network