version: "3.9"

services:

  postgres:
    image: postgres:14.2
    container_name: shop-orch-postgres
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: shop-orch
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:9292
    links:
      - postgres
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bundle exec rackup --host=0.0.0.0

volumes:
  postgres:

networks:
  default:
      name: shop-local-network