version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    volumes:
      - redis:/var/lib/redis/data

  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:9292
    links:
      - postgres
      - redis
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bundle exec rackup --host=0.0.0.0

volumes:
  postgres:
  redis: